on: 
  push:
    branches:
      - master
    tags:
      - "*"
jobs:
  validate_canonical_match:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - run: git config --global user.email "gary@sourceauditor.com"
      - run: git config --global user.name "License Publisher (maintained by Gary O'Neall)"
      - run: make deploy-license-data
        env:
          LICENSE_LIST_GITHUB_TOKEN: ${{ secrets.LICENSE_LIST_GITHUB_TOKEN }}
          SHA_FOR_GITHUB: ${{ github.sha }}
